import {
  card,
  cta,
  heroSlide,
  mediaAsset,
  portableContent,
  processStep,
  rtqFormConfig,
  seo,
  signatureUptimeSection,
  skillsCard
} from "./objects";
import {
  blogPost,
  capabilityPage,
  caseStudy,
  certificationOrAward,
  downloadAsset,
  educationPage,
  faq,
  foundationInitiative,
  homepage,
  industrialTrainingProgram,
  industryPage,
  leader,
  navigationSettings,
  partner,
  signatureUptimeSolution,
  siteSettings,
  solutionsOverviewPage,
  solutionPage,
  tvetDevelopment,
  universityPartnership
} from "./documents";

export const schemaTypes = [
  seo,
  mediaAsset,
  cta,
  card,
  skillsCard,
  processStep,
  heroSlide,
  signatureUptimeSection,
  rtqFormConfig,
  portableContent,
  siteSettings,
  navigationSettings,
  signatureUptimeSolution,
  homepage,
  solutionsOverviewPage,
  solutionPage,
  industryPage,
  capabilityPage,
  caseStudy,
  certificationOrAward,
  partner,
  leader,
  blogPost,
  downloadAsset,
  faq,
  educationPage,
  universityPartnership,
  industrialTrainingProgram,
  foundationInitiative,
  tvetDevelopment
];
